metadata:
  description: >-
    Sample nco config
user:
  RUN_ENVIR: nco
  MACHINE: hera
  ACCOUNT: an_account
workflow:
  EXPT_SUBDIR: test_nco
  CCPP_PHYS_SUITE: FV3_GFS_v16
  DATE_FIRST_CYCL: '2022040700'
  DATE_LAST_CYCL: '2022040700'
  FCST_LEN_HRS: 6
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
workflow_switches:
  RUN_TASK_MAKE_GRID: false
  RUN_TASK_MAKE_OROG: false
  RUN_TASK_MAKE_SFC_CLIMO: false
nco:
  NET: rrfs
  model_ver: v1.0
  RUN: rrfs_test
  OPSROOT: ""
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: grib2
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 3
  FV3GFS_FILE_FMT_LBCS: grib2
task_run_fcst:
  WTIME_RUN_FCST: 01:00:00
  WRITE_DOPOST: true
  QUILTING: true
  PREDEF_GRID_NAME: RRFS_CONUS_25km
task_run_post:
  POST_OUTPUT_DOMAIN_NAME: conus_25km
