metadata:
  description: >-
    Sample nco config
user:
  RUN_ENVIR: nco
  MACHINE: hera
  ACCOUNT: an_account
workflow:
  USE_CRON_TO_RELAUNCH: false
  EXPT_SUBDIR: test_nco
  CCPP_PHYS_SUITE: FV3_GFS_v16
  PREDEF_GRID_NAME: RRFS_CONUS_25km
  DATE_FIRST_CYCL: '2022040700'
  DATE_LAST_CYCL: '2022040700'
  FCST_LEN_HRS: 6
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
nco:
  NET: rrfs
  model_ver: v1.0
  RUN: rrfs_test
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: grib2
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 3
  FV3GFS_FILE_FMT_LBCS: grib2
task_run_fcst:
  WRITE_DOPOST: true
  QUILTING: true
task_plot_allvars:
  COMOUT_REF: ""
task_run_post:
  POST_OUTPUT_DOMAIN_NAME: conus_25km
rocoto:
  tasks:
    taskgroups: '{{ ["parm/wflow/coldstart.yaml", "parm/wflow/post.yaml"]|include }}'
    metatask_run_ensemble:
      task_run_fcst_mem#mem#:
        walltime: 01:00:00
